config/routes.rb
Rails.application.routes.draw do

  resources :nomenclators do
    resources :items
  end

  resources :systems do
    resources :attribs do
    end
    resources :patients do
      resources :attvalues
    end
  end

  get 'systems/:id/queries' => 'systems#dynamic_queries', as: :dynamic_queries

  root 'systems#index'

end

app/models/attrib.rb
class Attrib < ActiveRecord::Base
  belongs_to :system
  has_many :attvalues, dependent: :destroy

  ATTR_TYPES = %w(string text integer float date datetime time nomenclator)

  validates :name, presence: true
  #validates_numericality_of :attr_type
  #validates_format_of :attr_type
  validates :attr_type, inclusion: ATTR_TYPES

  enum attr_type: %i(string text integer float date datetime time nomenclator)

  def get_attrib_system_name(system_id)
    return System.find_by(id:system_id).name
  end
end

app/controllers/attribs_controller.rb
class AttribsController < ApplicationController
  before_action :set_attrib, only: [:show, :edit, :update, :destroy]

  # GET /attribs
  # GET /attribs.json
  def index
    #query = "system_id = #{params[:system_id]}"
    @attribs = Attrib.where(system_id: params[:system_id]).page(params[:page]).per(10)
    params[:system_name] = System.find_by(id: params[:system_id]).name
    #@attribs = Attrib.all
  end

  # GET /attribs/1
  # GET /attribs/1.json
  def show
  end

  # GET /attribs/new
  def new
    @attrib = Attrib.new
    @attrib.system_id = params[:system_id]
  end

  # GET /attribs/1/edit
  def edit
  end

  # POST /attribs
  # POST /attribs.json
  def create
    #system = System.find(params[:system_id])
    @attrib = Attrib.new(attrib_params)

    respond_to do |format|
      if @attrib.save
        format.html { redirect_to system_attribs_path(@attrib.system_id), notice: 'Attrib was successfully created.' }
        format.json { render :show, status: :created, location: @attrib }
      else
        format.html { render :new }
        format.json { render json: @attrib.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attribs/1
  # PATCH/PUT /attribs/1.jsonF
  def update
    respond_to do |format|
      if @attrib.update(attrib_params)
        format.html { redirect_to system_attrib_path(@attrib.system_id, @attrib.id), notice: 'Attrib was successfully updated.' }
        format.json { render :show, status: :ok, location: @attrib }
      else
        format.html { render :edit }
        format.json { render json: @attrib.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attribs/1
  # DELETE /attribs/1.json
  def destroy
    @attrib.destroy
    respond_to do |format|
      format.html { redirect_to system_attribs_path(@attrib.system_id), notice: 'Attrib was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_attrib
    @attrib = Attrib.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:system_id, :name, :attr_type, :extra)
  end
end

app/helpers/attribs_helper.rb
module AttribsHelper
end

app/views/attribs/_form.html.erb
<%
   # TODO: arreglar esto que esta feo
   if @attrib.new_record?
     path_to_send = system_attribs_path(system_id:@attrib.system_id)
   else
     path_to_send = system_attrib_path(system_id:@attrib.system_id, id:@attrib.id)
   end
%>

<%= form_for @attrib, url: path_to_send, :html => { :class => "form-horizontal attrib" } do |f| %>

    <% if @attrib.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@attrib.errors.count, "error") %> prohibited this attrib from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @attrib.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

   <div hidden="hidden" class="form-group">
     <%= f.label :system_id, :class => 'col-sm-2 control-label' %>
     <div class="col-sm-10">
       <%= f.text_field :system_id, :class => 'form-control' %>
     </div>
   </div>

  <div class="form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => 'form-control', placeholder: "Enter the name of the new Attribute" %>
    </div>
    <%= error_span(@attrib[:name]) %>
  </div>

  <div class="form-group">
    <%= f.label :attr_type, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.select :attr_type, Attrib::ATTR_TYPES, :class => 'form-control', placeholder: "Enter the type of the new Attribute" %>
    </div>
    <%= error_span(@attrib[:attr_type]) %>
  </div>

  <div class="form-group">
    <%= f.label :extra, :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :extra, :class => 'form-control', placeholder: "Enter an extra field of the new Attribute" %>
    </div>
    <%= error_span(@attrib[:extra]) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  system_attribs_path(@attrib.system_id), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/attribs/edit.html.erb
<%- model_class = Attrib -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attribs/index.html.erb
<%- model_class = Attrib -%>
<div class="page-header">
  <h1><%= params[:system_name] %> --> <%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:extra) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @attribs.each do |attrib| %>
      <tr>
        <td><%= attrib.name %></td>
        <td><%= attrib.attr_type %></td>
        <td>
          <% if attrib.extra.nil? or attrib.extra == '' %>
              ----
          <% else %>
              <%= attrib.extra %>
          <% end %>
        </td>
        <td>
          <%= link_to t('.show'),
                      system_attrib_path(system_id:attrib.system_id, id:attrib.id),
                      :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_system_attrib_path(system_id:attrib.system_id, id:attrib.id),
                      :class => 'btn btn-xs btn-warning' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      system_attrib_path(system_id:attrib.system_id, id:attrib.id),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= paginate @attribs %></p>

<%= content_for :sidebar do %>
    <li><%= link_to t('.new', :default => t("helpers.links.new")),
                new_system_attrib_path %></li>
    <li><%= link_to t('.back'), system_path(params[:system_id]) %></li>
<% end %>

app/views/attribs/new.html.erb
<%- model_class = Attrib -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/attribs/show.html.erb
<%- model_class = Attrib -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:system_id) %>:</strong></dt>
  <dd><%= @attrib.get_attrib_system_name(@attrib.system_id) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @attrib.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @attrib.attr_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:extra) %>:</strong></dt>
  <dd><%= @attrib.extra %></dd>
</dl>

<%= content_for :sidebar do %>
    <li><%= link_to t('.back', :default => t("helpers.links.back")),
                system_attribs_path  %></li>
    <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_system_attrib_path(@attrib.system_id, @attrib.id) %></li>
    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                system_attrib_path(@attrib.system_id, @attrib.id),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %></li>
<% end %>