config/routes.rb
Rails.application.routes.draw do

  resources :nomenclators do
    resources :items
  end

  resources :systems do
    resources :attribs do
    end
    resources :patients do
      resources :attvalues
    end
  end

  get 'systems/:id/queries' => 'systems#dynamic_queries', as: :dynamic_queries

  root 'systems#index'

end

app/models/system.rb
class System < ActiveRecord::Base
  has_many :attribs, dependent:  :destroy
  has_and_belongs_to_many :patients

  validates :name, presence: true
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  before_action :set_system, only: [:show, :edit, :update, :destroy]

  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
  end

  # GET /systems/new
  def new
    @system = System.new
  end

  # GET /systems/1/edit
  def edit
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(system_params)

    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render :show, status: :created, location: @system }
      else
        format.html { render :new }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /systems/1
  # PATCH/PUT /systems/1.json
  def update
    respond_to do |format|
      if @system.update(system_params)
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { render :show, status: :ok, location: @system }
      else
        format.html { render :edit }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system.destroy
    respond_to do |format|
      format.html { redirect_to systems_url, notice: 'System was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_system
      @system = System.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def system_params
      params.require(:system).permit(:name, :description)
    end


  #### DYNAMIC QUERIES

  def dynamic_queries
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.erb
<%= form_for(@system, html: {class: "form-horizontal"}) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter the name of the new System" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
        <%= f.text_area :description, class: "form-control", placeholder: "Enter the description of the new System" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    systems_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/systems/edit.html.erb
<h1>Editing system</h1>

<%= render 'form' %>

<%= content_for :sidebar do %>
    <li><%= link_to 'Back', systems_path %></li>
<% end %>

app/views/systems/index.html.erb
<h1><%= t('.systems') %></h1>

<% @systems.each do |system| %>
    <div class="well well-small">
      <div class="row">
        <div class="col-md-10">
          <h4><%= link_to system.name, system %></h4>
          <p><%= system.description %></p>
        </div>
        <div class="col-md-2">
          <%= link_to t('.edit'), edit_system_path(system), :class => 'btn btn-warning btn-sm' %> <br> <br>
          <%= link_to t('.destroy'), system, method: :delete, data: { confirm: 'Are you sure?' },
            :class => 'btn btn-danger btn-sm' %>
        </div>
      </div>
    </div>
<% end %>

<br>

<%= content_for :sidebar do %>
    <li><%= link_to t('.new System'), new_system_path %></li>
<% end %>

app/views/systems/new.html.erb
<h1>New system</h1>

<%= render 'form' %>

<%= content_for :sidebar do %>
    <li><%= link_to 'Back', systems_path %></li>
<% end %>

app/views/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @system.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @system.description %>
</p>


<%= content_for :sidebar do %>
    <li><%= link_to t('.edit'), edit_system_path(@system) %></li>
    <li><%= link_to t('.attributes'), system_attribs_path(@system) %></li>
    <li><%= link_to t('.patients'), system_patients_path(@system) %></li>
    <li><a href="<%= dynamic_queries_path %>"><%= t('.queries') %></a></li>
    <li><%= link_to t('.back'), systems_path %></li>
<% end %>