config/routes.rb
Rails.application.routes.draw do

  resources :nomenclators do
    resources :items
  end

  resources :systems do
    resources :attribs do
    end
    resources :patients do
      resources :attvalues
    end
  end

  get 'systems/:id/queries' => 'systems#dynamic_queries', as: :dynamic_queries

  root 'systems#index'

end

app/models/nomenclator.rb
class Nomenclator < ActiveRecord::Base
  has_many :items, dependent:  :destroy
  validates :name, presence: true
end

app/controllers/nomenclators_controller.rb
class NomenclatorsController < ApplicationController
  before_action :set_nomenclator, only: [:show, :edit, :update, :destroy]

  # GET /nomenclators
  # GET /nomenclators.json
  def index
    @nomenclators = Nomenclator.all.page(params[:page]).per(10)
  end

  # GET /nomenclators/1
  # GET /nomenclators/1.json
  def show
  end

  # GET /nomenclators/new
  def new
    @nomenclator = Nomenclator.new
  end

  # GET /nomenclators/1/edit
  def edit
  end

  # POST /nomenclators
  # POST /nomenclators.json
  def create
    @nomenclator = Nomenclator.new(nomenclator_params)

    respond_to do |format|
      if @nomenclator.save
        format.html { redirect_to @nomenclator, notice: 'Nomenclator was successfully created.' }
        format.json { render :show, status: :created, location: @nomenclator }
      else
        format.html { render :new }
        format.json { render json: @nomenclator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nomenclators/1
  # PATCH/PUT /nomenclators/1.json
  def update
    respond_to do |format|
      if @nomenclator.update(nomenclator_params)
        format.html { redirect_to @nomenclator, notice: 'Nomenclator was successfully updated.' }
        format.json { render :show, status: :ok, location: @nomenclator }
      else
        format.html { render :edit }
        format.json { render json: @nomenclator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nomenclators/1
  # DELETE /nomenclators/1.json
  def destroy
    @nomenclator.destroy
    respond_to do |format|
      format.html { redirect_to nomenclators_url, notice: 'Nomenclator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nomenclator
      @nomenclator = Nomenclator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nomenclator_params
      params.require(:nomenclator).permit(:name, :description)
    end
end

app/helpers/nomenclators_helper.rb
module NomenclatorsHelper
end

app/views/nomenclators/_form.html.erb
<%= form_for @nomenclator, :html => { :class => "form-horizontal nomenclator" } do |f| %>

  <% if @nomenclator.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@nomenclator.errors.count, "error") %> prohibited this nomenclator from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @nomenclator.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'col-sm-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control', placeholder: "Enter the name of the new Nomenclator" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'col-sm-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control', placeholder: "Enter a description for the new Nomenclator" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                nomenclators_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/nomenclators/edit.html.erb
<%- model_class = Nomenclator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nomenclators/index.html.erb
<%- model_class = Nomenclator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <!--<th><%= model_class.human_attribute_name(:created_at) %></th>-->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @nomenclators.each do |nomenclator| %>
      <tr>
        <td><%= nomenclator.name %></td>
        <td><%= nomenclator.description %></td>
        <td>
          <%= link_to t('.show'), nomenclator_path(nomenclator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_nomenclator_path(nomenclator), :class => 'btn btn-xs btn-warning' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      nomenclator_path(nomenclator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= paginate @nomenclators %></p>

<%= content_for :sidebar do %>
    <li><%= link_to t('.new', :default => t("helpers.links.new")),
                new_nomenclator_path %></li>
<% end %>

app/views/nomenclators/new.html.erb
<%- model_class = Nomenclator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/nomenclators/show.html.erb
<%- model_class = Nomenclator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @nomenclator.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @nomenclator.description %></dd>
</dl>


<%= content_for :sidebar do %>
    <li><%= link_to t('.values'), nomenclator_items_path(@nomenclator) %></li>
    <li><%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_nomenclator_path(@nomenclator) %></li>
    <li><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  nomenclator_path(@nomenclator),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %></li>
    <li><%= link_to t('.back', :default => t("helpers.links.back")),
                nomenclators_path %></li>
<% end %>